version: "3.8"

services:
  #https://docs.localstack.cloud/getting-started/installation/#docker-compose
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    build:
      context: ./local/
      dockerfile: ./localstack.Dockerfile
    ports:
      - "4566:4566"         
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
  
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - "./local/sql:/docker-entrypoint-initdb.d"